services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend-us
      - backend-eu

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  db-us:
    image: postgres:14
    container_name: db-us
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: property_db
    volumes:
      - postgres-data-us:/var/lib/postgresql/data
      - ./seeds:/docker-entrypoint-initdb.d:ro

  db-eu:
    image: postgres:14
    container_name: db-eu
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: property_db
    volumes:
      - postgres-data-eu:/var/lib/postgresql/data
      - ./seeds:/docker-entrypoint-initdb.d:ro

  backend-us:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-us
    environment:
      - REGION=us
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db-us:5432/property_db
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=property-updates
    depends_on:
      - db-us
      - kafka

  backend-eu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-eu
    environment:
      - REGION=eu
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db-eu:5432/property_db
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=property-updates
    depends_on:
      - db-eu
      - kafka

volumes:
  postgres-data-us:
  postgres-data-eu:
